name: Build, Release and Upload Python Package

on: 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipreqs and other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel pipreqs

    - name: Modify specific files
      run: |
        sed -i '1s/^\xEF\xBB\xBF//' temp_folder_crappy/crappy/blocks/videoExtenso.py || true
        sed -i '1s/^\xEF\xBB\xBF//' temp_folder_crappy/crappy/actuator/biotens.py || true
        sed -i '1s/^\xEF\xBB\xBF//' temp_folder_crappy/crappy/actuator/biaxe.py || true

    - name: Generate requirements.txt
      run: |
        /app/venv_claiton/bin/pipreqs temp_folder_crappy --force

    - name: Modify requirements.txt
      run: |
        sed -i '/^Pillow==10.0.0/d' temp_folder_crappy/requirements.txt
        sed -i '/^pywinauto==/d' temp_folder_crappy/requirements.txt
        sed -i '/^picamera==/d' temp_folder_crappy/requirements.txt
        sed -i '/^pycuda==/d' temp_folder_crappy/requirements.txt
        sed -i 's/^docx==.*/python-docx/' temp_folder_crappy/requirements.txt
        sed -i '/^pyppeteer==/d' temp_folder_crappy/requirements.txt
        sed -i 's/^scikit-image0.0/scikit-image/' temp_folder_crappy/requirements.txt
        sed -i 's/^skimage==0.0/scikit-image/' temp_folder_crappy/requirements.txt

